### ISSUE TITLE
[Suggestion] Port to 1.12.2

### ISSUE THREAD

**Issue by x8vxv8x** [CCr4ft3r/lightspeed#10]
many popular modpacks are on 1.12.2 ，so it would be great if this mod could be ported to 1.12.2 as it could help save loading time with modpacks

**Comment by CCr4ft3r** [comment]
Sorry to inform you that I'm not going to backport Lightspeed to 1.12.2. Let me explain the reasons:

I did some launch profiling and the most majority of current Lightspeed optimizations wouldn't be a really noticeable improvement in terms of launch time since in 1.12.2 there are completely other CPU hot spots.
Furthermore many hot spots also seems to be caused by classes of forges mod loading system and modules, that cannot be changed by using mixins (like Lightspeed currently does).

It would be probably possible by using another bytecode manipulation framework like JavaAssist instead of Mixin.
But that is only a speculation. Maybe it would require even more work and adapations to get optimizations work.
I also never did modding for 1.12.2 - so even if I would find a way of making it work it would probably take a small eternity.
I'm not even sure if making mod loading parallelized would be possible, since all other concepts like registries would need to be or to be made thread-safe.

Perhaps these are some of the reasons why there's no similar mods for 1.12.2 that improves launch time by at least 50% even after 6 years. 

These explanations may sound like lame excuses or lies to you, but that's my current assessment and state of knowledge. 
Even myself was convinced back then to be able to backport it. 

Sorry.

**Comment by CCr4ft3r** [comment]
It's probably not a replacement but this new mod states to reduces load time a bit: [VintageFix](https://www.curseforge.com/minecraft/mc-mods/vintagefix)
