### ISSUE TITLE
[Feature Request] Allow mixin configuration

### ISSUE THREAD

**Issue by Kasualix** [CCr4ft3r/lightspeed#13]
Hi there, it would be nice if you can categorize your mixin code in more details ＆ use sodium's config system to make them easily configurable.
example: https://github.com/embeddedt/ModernFix/tree/main/src/main/java/org/embeddedt/modernfix/core

**Comment by CCr4ft3r** [comment]
Hi :) In my opinion, configurability only becomes useful if there are a lot of incompatibilities. Since the core concept of Lightspeed is overall compatibility no user should have to worry about what config option they need to disable, so that different mods work together.
Is there any advantage of having this feature?

**Comment by Kasualix** [comment]
Cuz ModernFix + Lightspeed causes negative optimization.
They do patch the similar code in Minecraft so it's needed to disable some of the mixins on both sides to make them perfectly compatible

**Comment by CCr4ft3r** [comment]
Please provide launch times for this: 
Launch time only with Lightspeed
Launch time only with ModernFix
Launch time with both Lightspeed and ModernFix

I will then look into it.

**Comment by Kasualix** [comment]
Oh, my bad, it seems to be fixed by ModernFix now.
Sorry for the bothering

**Comment by CCr4ft3r** [comment]
No need to be sorry :)
