### ISSUE TITLE
A file output for how long each mod takes to load.

### ISSUE THREAD

**Issue by DraTrav** [CCr4ft3r/lightspeed#29]
A way to list how long each mod takes to load. That way you have an idea about what mods are slowing down loading time.

**Comment by CCr4ft3r** [comment]
Lightspeed focuses on optimizing launch related source code of Minecraft and Forge. Because these two caused the majority of the launch time (according to my observations and performance profiling). The modpacks I profiled did not have striking CPU hotspots at launch time caused by a particular mod.

In general this is a good idea, but it would be better to include this feature in a performance profiler mod like Spark.
It has already been suggested on their GitHub: https://github.com/lucko/spark/issues/289
I would recommend upvoting this request.
