### ISSUE TITLE
Modrinth

### ISSUE THREAD

**Issue by MattyWalker1** [CCr4ft3r/lightspeed#3]
You should upload this to [Modrinth](https://modrinth.com/mods) it is a great alternative to CurseForge and it might be easier for people to find it there since they have a category for optimization.

**Comment by CCr4ft3r** [comment]
Thank you for this suggestion. I will take a look into it :)

**Comment by CCr4ft3r** [comment]
Done and Approved: [https://modrinth.com/mod/lightspeed](https://modrinth.com/mod/lightspeed)
Thx again for the idea👍

**Comment by ColonelGerdauf** [comment]
I should note that the latest version available on Modrinth (1.0.2) is out of date compared to CurseForge (1.0.5).

**Comment by CCr4ft3r** [comment]
After creating more mods, I noticed that parallel support for two platforms becomes more expensive. Therefore I will only update my mods on CurseForge

**Comment by ColonelGerdauf** [comment]
That is unfortunate, as Modrinth is an easier platform to work with, and download mods from. Curse's advantage is the potential inclusion in modpacks, where Curse still has significant advantage due to the staying power and legacy.

When in Prism (a launcher), I have noticed considerable difficult in downloading the Curse copy of Lightspeed, repeatedly citing "No Versions Found!". This is for both 1.16.5, and 1.19.2. This forces me to download from Modrinth, which many including myself honestly prefer anyways.

**Comment by CCr4ft3r** [comment]
I think I will need to enable 3rd party sharing for the mod. Please try again. I enabled it.

**Comment by ColonelGerdauf** [comment]
Still the same result.

**Comment by CCr4ft3r** [comment]
I agree with your opinion on Modrinth. But currently more users are familiar with CurseForge. I will switch to Modrinth when the majority has been moved

**Comment by CCr4ft3r** [comment]
Maybe this option is still cached on the server. Should work after some days.

**Comment by ColonelGerdauf** [comment]
Took a few moments, but it is back.

**Comment by ColonelGerdauf** [comment]
Actually, this seems to have been reversed. Now it is back to "No valid version found".
