### ISSUE TITLE
Lightspeed - Launch optimizations

### ISSUE THREAD

**Issue by INS-1** [CCr4ft3r/lightspeed#34]
1.19.2 When I open the game It is working in task manager but CPU is 0% and no game window comes up. Please help. T^T
[latest.log](https://github.com/CCr4ft3r/lightspeed/files/13694643/latest.log)
![Screenshot 2023-12-17 110248](https://github.com/CCr4ft3r/lightspeed/assets/154037266/b7893396-3973-463b-8694-44f52c888f1a)

**Comment by CCr4ft3r** [comment]
This issue doesn't seem to be caused by Lightspeed. There are multiple missing library mods:

- 	Mod ID: 'balm', Requested by: 'waystones', Expected range: '[4.1.0,)', Actual version: '[MISSING]'
- 	Mod ID: 'resourcefullib', Requested by: 'endermanoverhaul', Expected range: '[1.1.24,)', Actual version: '[MISSING]'
- 	Mod ID: 'resourcefulconfig', Requested by: 'creeperoverhaul', Expected range: '[1.0.20,)', Actual version: '[MISSING]'
- 	Mod ID: 'resourcefulconfig', Requested by: 'endermanoverhaul', Expected range: '[1.0.20,)', Actual version: '[MISSING]'
- 	Mod ID: 'forgeendertech', Requested by: 'adfinders', Expected range: '[10.0.6.0,)', Actual version: '[MISSING]'

You'll need to add them. After that Minecraft should start as usually.

**Comment by INS-1** [comment]
I don't know much about how mods work, but may I ask how you can figure out what mods I'm missing?

**Comment by CCr4ft3r** [comment]
Sure. 
Every mod created for Minecraft can declare their dependent mods in a specific file inside their jar file. 
Forge, the mod loader you are using, checks at startup that all required mods are present in the mods folder.
If any of these dependencies are missing, Forge will log this in your latest.log.
So in your latest.log you can search for the following error: Missing or unsupported mandatory dependencies (or navigate to line 128).
There's the list of missing mods I've posted earlier.

**Comment by INS-1** [comment]
Wow, you are amazing. Thank you. :D

**Comment by CCr4ft3r** [comment]
no problem :)
