### ISSUE TITLE
1.20.1 support?

### ISSUE THREAD

**Issue by ryleu** [CCr4ft3r/lightspeed#35]

**Comment by CCr4ft3r** [comment]
Forge got better by each version. 
With 1.18.2 users get the most benefit by using Lightspeed approx. 50% up to 75% - it saved several minutes of the launch time. By 1.19.2 it was only 25%. I did some testing with 1.20 and a modpack consisting of more than 200 mods started in just about 74 seconds. In my opinion that's already quite acceptable. The actual benefit for 1.20 would be 10-15 seconds at most. That's not really worth it.

**Comment by ryleu** [comment]
would be good to indicate that in your readme

**Comment by 1111317** [comment]
Mobile launchers, like the Pojav Launcher, still take several minutes to load a lot of mods, Lightspeed still makes sense of it?

**Comment by mateus3c** [comment]
Honesty, 10-15 seconds do make a nice difference not only for normal gameplay but for debugging too!
I play with 600+ mods so I really hope to see the 1.20.1 version of the mod because honestly, it can still help a lot.

btw, couldn't that improvement of 10-15 seconds change depending of the hardware?

**Comment by Hakuyako** [comment]
Even though 1.20.1 no longer takes a lot of time to launch, 15-second change is still worth it.

For a game that opened frequently, saving 20% launch time can effectively improve experience.
Everyone wants to make the game as light as possible, so that the game can be opened and closed at any time, without worrying about the time cost of launching the game.

This is a good project and I hope it can be continued.
