### ISSUE TITLE
[Crash]: Crash during game starting

### ISSUE THREAD

**Issue by ghost** [CCr4ft3r/lightspeed#7]
### Mod Loader

Forge 36.2.39

### Minecraft Version

1.16.5

### Mod Version

1.0.2

### Notes

Note: Conflict with ModernFix. I am reporting this problem to the developers of both mods.

1. Run Minecraft.
2. Mod loader loading screen freezes.
3. Game crashes.

### Crash Report

[crash-2023-03-18_20.18.58-client.txt](https://github.com/CCr4ft3r/lightspeed/files/11009897/crash-2023-03-18_20.18.58-client.txt)

**Comment by embeddedt** [comment]
@CCr4ft3r One of us will need to turn off the resource pack caching on their side. They are basically the same implementation which causes conflicts (not sure why this works out of the box on 1.18).

**Comment by CCr4ft3r** [comment]
It crashes for 1.16.5 because ModernFix overrides the getResources method:
https://github.com/embeddedt/ModernFix/blob/38a47766262c1f888f275c201bb7f0f7fb6c32dc/src/main/java/org/embeddedt/modernfix/mixin/perf/resourcepacks/ModFileResourcePackMixin.java#L115

For 1.18.2 you inject a callback like Lightspeed which is more compatiblity friendly regarding SpongePowereds strategy of supporting multiple mixins for the same injection points:
https://github.com/embeddedt/ModernFix/blob/36a7b93d803f8385bd4fe0248e4475dc7cb8de53/src/main/java/org/embeddedt/modernfix/mixin/perf/modern_resourcepacks/PathResourcePackMixin.java#L129

If you replace the override with a mixin callback it should work fine.

**Comment by embeddedt** [comment]
Alright, I will tweak that on Monday.

**Comment by CCr4ft3r** [comment]
Thx 👍
